#[[docs]]
#  name = "Help"
#  weight = 10
#  identifier = "help"
#  url = "/docs/help/"

#[[main]]
#  name = "Styles"
#  url = "/docs/styles/"
#  weight = 10

# [[footer]]
#   name = "Privacy"
#   url = "/privacy-policy/"
#   weight = 10
